name: Main Workflow (Python)

# События, запускающие процесс
on:
  # Git push develop
  push:
    branches:
      - develop

  # Each day on 00:00 UTC
  # https://crontab.guru/every-day
  schedule:
    - cron: '0 0 * * *'

jobs:
  # job title
  build:
    runs-on: ubuntu-latest

    steps:
      # Get the repository code
      - name: Checkout repository
        uses: actions/checkout@v3
      # Install Python 3.9
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      # Install and configure python environment using Poetry
      - name: Install poetry
        run: python -m pip install poetry==1.3.2
      - name: Configure poetry
        run: python -m poetry config virtualenvs.in-project true
      - name: Install dependencies
        run: python -m poetry install

      - name: Generate pages
        run: python -m poetry run python src/main.py
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: $
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
